### ISSUE TITLE
Install fails installing pillow

### ISSUE THREAD

**Issue by sebimalwieder** [chme/pidi-mpris#1]
Hey there,

after cloning onto my Pi Zero I was trying to run the setup.py script. 

Here's the output.

```
pi@airpirate:~/pidi-mpris $ sudo python3 setup.py install
running install
running bdist_egg
running egg_info
writing pidi_mpris.egg-info/PKG-INFO
writing dependency_links to pidi_mpris.egg-info/dependency_links.txt
writing entry points to pidi_mpris.egg-info/entry_points.txt
writing requirements to pidi_mpris.egg-info/requires.txt
writing top-level names to pidi_mpris.egg-info/top_level.txt
reading manifest file 'pidi_mpris.egg-info/SOURCES.txt'
writing manifest file 'pidi_mpris.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv6l/egg
running install_lib
running build_py
creating build/bdist.linux-armv6l/egg
creating build/bdist.linux-armv6l/egg/pidi_mpris
copying build/lib/pidi_mpris/screens.py -> build/bdist.linux-armv6l/egg/pidi_mpris
copying build/lib/pidi_mpris/player.py -> build/bdist.linux-armv6l/egg/pidi_mpris
copying build/lib/pidi_mpris/buttons.py -> build/bdist.linux-armv6l/egg/pidi_mpris
copying build/lib/pidi_mpris/__init__.py -> build/bdist.linux-armv6l/egg/pidi_mpris
copying build/lib/pidi_mpris/display.py -> build/bdist.linux-armv6l/egg/pidi_mpris
copying build/lib/pidi_mpris/mpris.py -> build/bdist.linux-armv6l/egg/pidi_mpris
copying build/lib/pidi_mpris/util.py -> build/bdist.linux-armv6l/egg/pidi_mpris
copying build/lib/pidi_mpris/main.py -> build/bdist.linux-armv6l/egg/pidi_mpris
byte-compiling build/bdist.linux-armv6l/egg/pidi_mpris/screens.py to screens.cpython-37.pyc
byte-compiling build/bdist.linux-armv6l/egg/pidi_mpris/player.py to player.cpython-37.pyc
byte-compiling build/bdist.linux-armv6l/egg/pidi_mpris/buttons.py to buttons.cpython-37.pyc
byte-compiling build/bdist.linux-armv6l/egg/pidi_mpris/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-armv6l/egg/pidi_mpris/display.py to display.cpython-37.pyc
byte-compiling build/bdist.linux-armv6l/egg/pidi_mpris/mpris.py to mpris.cpython-37.pyc
byte-compiling build/bdist.linux-armv6l/egg/pidi_mpris/util.py to util.cpython-37.pyc
byte-compiling build/bdist.linux-armv6l/egg/pidi_mpris/main.py to main.cpython-37.pyc
installing package data to build/bdist.linux-armv6l/egg
running install_data
creating build/bdist.linux-armv6l/egg/EGG-INFO
copying pidi_mpris.egg-info/PKG-INFO -> build/bdist.linux-armv6l/egg/EGG-INFO
copying pidi_mpris.egg-info/SOURCES.txt -> build/bdist.linux-armv6l/egg/EGG-INFO
copying pidi_mpris.egg-info/dependency_links.txt -> build/bdist.linux-armv6l/egg/EGG-INFO
copying pidi_mpris.egg-info/entry_points.txt -> build/bdist.linux-armv6l/egg/EGG-INFO
copying pidi_mpris.egg-info/requires.txt -> build/bdist.linux-armv6l/egg/EGG-INFO
copying pidi_mpris.egg-info/top_level.txt -> build/bdist.linux-armv6l/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/pidi_mpris-1.0.0-py3.7.egg' and adding 'build/bdist.linux-armv6l/egg' to it
removing 'build/bdist.linux-armv6l/egg' (and everything under it)
Processing pidi_mpris-1.0.0-py3.7.egg
Removing /usr/local/lib/python3.7/dist-packages/pidi_mpris-1.0.0-py3.7.egg
Copying pidi_mpris-1.0.0-py3.7.egg to /usr/local/lib/python3.7/dist-packages
pidi-mpris 1.0.0 is already the active version in easy-install.pth
Installing pidi-mpris script to /usr/local/bin

Installed /usr/local/lib/python3.7/dist-packages/pidi_mpris-1.0.0-py3.7.egg
Processing dependencies for pidi-mpris==1.0.0
Searching for pillow
Reading https://pypi.org/simple/pillow/
Downloading https://files.pythonhosted.org/packages/2b/06/93bf1626ef36815010e971a5ce90f49919d84ab5d2fa310329f843a74bc1/Pillow-8.0.1.tar.gz#sha256=11c5c6e9b02c9dac08af04f093eb5a2f84857df70a7d4a6a6ad461aca803fb9e
Best match: Pillow 8.0.1
Processing Pillow-8.0.1.tar.gz
Writing /tmp/easy_install-a44_py1g/Pillow-8.0.1/setup.cfg
Running Pillow-8.0.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-a44_py1g/Pillow-8.0.1/egg-dist-tmp-vbu72qcz
warning: no files found matching '*.c'
warning: no files found matching '*.h'
warning: no files found matching '*.sh'
warning: no previously-included files found matching '.appveyor.yml'
warning: no previously-included files found matching '.coveragerc'
warning: no previously-included files found matching '.editorconfig'
warning: no previously-included files found matching '.readthedocs.yml'
warning: no previously-included files found matching 'codecov.yml'
warning: no previously-included files matching '.git*' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
no previously-included directories found matching '.ci'


The headers or library files could not be found for jpeg,
a required dependency when compiling Pillow from source.

Please see the install instructions at:
   https://pillow.readthedocs.io/en/latest/installation.html

Traceback (most recent call last):
  File "/tmp/easy_install-a44_py1g/Pillow-8.0.1/setup.py", line 901, in <module>
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 24, in run
    self.build()
  File "/usr/lib/python3.7/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_ext')
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 78, in run
    _build_ext.run(self)
  File "/usr/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/tmp/easy_install-a44_py1g/Pillow-8.0.1/setup.py", line 698, in build_extensions
__main__.RequiredDependencyException: jpeg

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-a44_py1g/Pillow-8.0.1/setup.py", line 914, in <module>
__main__.RequiredDependencyException: 

The headers or library files could not be found for jpeg,
a required dependency when compiling Pillow from source.

Please see the install instructions at:
   https://pillow.readthedocs.io/en/latest/installation.html



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 44, in <module>
    python_requires='>=3.6')
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 443, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 685, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 732, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 777, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 704, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 730, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 915, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1183, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1169, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python3/dist-packages/setuptools/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-a44_py1g/Pillow-8.0.1/setup.py", line 914, in <module>
setuptools.sandbox.UnpickleableException: RequiredDependencyException('\n\nThe headers or library files could not be found for jpeg,\na required dependency when compiling Pillow from source.\n\nPlease see the install instructions at:\n   https://pillow.readthedocs.io/en/latest/installation.html\n\n')
```

Could you maybe also provide some setup instructions?

Kind regards, 
Seb

**Comment by chme** [comment]
Hi @sebastiannoell,

great to hear you gave this a try!

On my RPi I installed the following python packages from the Raspberry Pi OS repository:

```
sudo apt install python3-rpi.gpio python3-spidev python3-pip python3-pil python3-numpy
```

(From the install instruction for the ST7789: https://github.com/pimoroni/st7789-python)

To install "pidi-mpris" I am then using pip3 (from the root folder of the local clone):

```
pip3 install .
```

(Uninstall should then be possible with `pip3 uninstall .`)

Let me know if this works.

Regards,
Christian
